version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgresUser@2345
      POSTGRES_PASSWORD: postgresPassword@5432
      POSTGRES_DB: collector
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - collDb

volumes:
  postgres_data:
    driver: local
